; This file is auto generated by cgn::MSVCTrampo

EXTERN ?find@GlobalSymbol@cgn@@SAPEAXPEBD@Z :PROC
.const
  msvc_trampo_0 DB "?func1_inc@@YAHAEAH@Z",0
  msvc_trampo_1 DB "?func1@@YA?AUMyTypeA@@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z",0
  msvc_trampo_2 DB "?func1_arr@@YA?AV?$vector@UMyTypeA@@V?$allocator@UMyTypeA@@@std@@@std@@PEBUMyTypeA@@@Z",0

.code
  ?func1_inc@@YAHAEAH@Z PROC
    sub rsp, 30h
    mov [rsp + 10h], rcx
    mov [rsp + 18h], rdx
    mov [rsp + 20h], r8
    mov [rsp + 28h], r9
    lea rcx, msvc_trampo_0
    call ?find@GlobalSymbol@cgn@@SAPEAXPEBD@Z
    mov rcx, [rsp + 10h]
    mov rdx, [rsp + 18h]
    mov r8, [rsp + 20h]
    mov r9, [rsp + 28h]
    add rsp, 30h
    jmp rax
  ?func1_inc@@YAHAEAH@Z ENDP

  ?func1@@YA?AUMyTypeA@@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z PROC
    sub rsp, 30h
    mov [rsp + 10h], rcx
    mov [rsp + 18h], rdx
    mov [rsp + 20h], r8
    mov [rsp + 28h], r9
    lea rcx, msvc_trampo_1
    call ?find@GlobalSymbol@cgn@@SAPEAXPEBD@Z
    mov rcx, [rsp + 10h]
    mov rdx, [rsp + 18h]
    mov r8, [rsp + 20h]
    mov r9, [rsp + 28h]
    add rsp, 30h
    jmp rax
  ?func1@@YA?AUMyTypeA@@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z ENDP

  ?func1_arr@@YA?AV?$vector@UMyTypeA@@V?$allocator@UMyTypeA@@@std@@@std@@PEBUMyTypeA@@@Z PROC
    sub rsp, 30h
    mov [rsp + 10h], rcx
    mov [rsp + 18h], rdx
    mov [rsp + 20h], r8
    mov [rsp + 28h], r9
    lea rcx, msvc_trampo_2
    call ?find@GlobalSymbol@cgn@@SAPEAXPEBD@Z
    mov rcx, [rsp + 10h]
    mov rdx, [rsp + 18h]
    mov r8, [rsp + 20h]
    mov r9, [rsp + 28h]
    add rsp, 30h
    jmp rax
  ?func1_arr@@YA?AV?$vector@UMyTypeA@@V?$allocator@UMyTypeA@@@std@@@std@@PEBUMyTypeA@@@Z ENDP

end
