// abseil asan failed test
// If Abseil is built with CMake without assigning -fsanitize=address, and the user assigns it later, the following error will occur.
//
// absl::flat_hash_map<std::string, Descriptor::WellKnownType>  //descriptor.cc:1610
// these code triggered an asan failed for abseil-cpp git_ver=4447c7562e3bc702ade25105912dce503f0c4010
//
// AddressSanitizer:DEADLYSIGNAL
// =================================================================
// ==1659080==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000364524 bp 0x7ffe1781f930 sp 0x7ffe1781f910 T0)
// ==1659080==The signal is caused by a READ memory access.
// ==1659080==Hint: address points to the zero page.
//     #0 0x364524 in absl::lts_20240722::container_internal::CommonFieldsGenerationInfoEnabled::generation() const /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:982:39
//     #1 0x362914 in bool absl::lts_20240722::container_internal::HashSetResizeHelper::InitializeSlots<std::allocator<char>, 88ul, false, false, 8ul>(absl::lts_20240722::container_internal::CommonFields&, std::allocator<char>, absl::lts_20240722::container_internal::ctrl_t, unsigned long, unsigned long) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:2049:45
//     #2 0x361987 in absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::resize_impl(absl::lts_20240722::container_internal::CommonFields&, unsigned long, absl::lts_20240722::container_internal::HashtablezInfoHandle) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:3629:23
//     #3 0x36c777 in absl::lts_20240722::container_internal::PrepareInsertNonSoo(absl::lts_20240722::container_internal::CommonFields&, unsigned long, absl::lts_20240722::container_internal::FindInfo, absl::lts_20240722::container_internal::PolicyFunctions const&) /project/fable/cgn-design/@third_party/abseil-cpp/repo/absl/container/internal/raw_hash_set.cc:612:7
//     #4 0x35dc58 in std::pair<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::iterator, bool> absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::find_or_prepare_insert_non_soo<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:3823:29
//     #5 0x35c109 in std::pair<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::iterator, bool> absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::find_or_prepare_insert<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:3887:12
//     #6 0x35beee in std::pair<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::iterator, bool> absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable::operator()<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&>, std::tuple<MyData const&>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&>&&, std::tuple<MyData const&>&&) const /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:3453:20
//     #7 0x35bdf0 in decltype(std::declval<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable>()(std::declval<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const& const&>(), std::piecewise_construct, std::declval<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&>>(), std::declval<std::tuple<MyData const&>>())) absl::lts_20240722::container_internal::memory_internal::DecomposePairImpl<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::tuple<MyData const&>>(absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable&&, std::pair<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&>, std::tuple<MyData const&>>) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/container_memory.h:152:10
//     #8 0x35bd3f in decltype(memory_internal::DecomposePairImpl(std::forward<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable>(fp), PairArgs(std::forward<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&>(fp0)))) absl::lts_20240722::container_internal::DecomposePair<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&>(absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable&&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/container_memory.h:219:10
//     #9 0x35bc35 in decltype(absl::container_internal::DecomposePair(std::declval<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable>(), std::declval<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&>())) absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>::apply<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&>(absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable&&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/flat_hash_map.h:640:12
//     #10 0x35bbf5 in decltype(absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>::apply(std::forward<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable>(fp), std::forward<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&>(fp0))) absl::lts_20240722::container_internal::hash_policy_traits<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, void>::apply<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&, absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>>(absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::EmplaceDecomposable&&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/hash_policy_traits.h:134:12
//     #11 0x35bb65 in std::pair<absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::iterator, bool> absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::emplace<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&, 0>(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const&) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:3012:12
//     #12 0x35b94c in void absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::insert<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const*>(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const*, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData> const*) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:2966:36
//     #13 0x35712e in absl::lts_20240722::container_internal::raw_hash_set<absl::lts_20240722::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>, absl::lts_20240722::container_internal::StringHash, absl::lts_20240722::container_internal::StringEq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, MyData>>>::insert(std::initializer_list<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, MyData>>) /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:2975:5
//     #14 0x356b7e in main /project/fable/cgn-design/hello/pbcc/abseil_test.cpp:18:23
//     #15 0x7fbf8e6295cf in __libc_start_call_main (/lib64/libc.so.6+0x295cf) (BuildId: d78a44ae94f1d320342e0ff6c2315b2b589063f8)
//     #16 0x7fbf8e62967f in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2967f) (BuildId: d78a44ae94f1d320342e0ff6c2315b2b589063f8)
//     #17 0x27a524 in _start (/project/fable/cgn-design/cgn-out/obj/hello_/pbcc_/abseil_test_FFFFBB2A/abseil_test+0x27a524) (BuildId: 4b67f3d07e341bc1)
//
// AddressSanitizer can not provide additional info.
// SUMMARY: AddressSanitizer: SEGV /project/fable/cgn-design/cgn-out/obj/@third_party_/abseil-cpp_/absl_FFFFBB2A/install/include/absl/container/internal/raw_hash_set.h:982:39 in absl::lts_20240722::container_internal::CommonFieldsGenerationInfoEnabled::generation() const
// ==1659080==ABORTING
//

#include <iostream>
#include <string>
#include <absl/container/flat_hash_map.h>

struct MyData {
    int a;
    std::string b;
    double c;
    bool d;
}x, y, z;

int main()
{
    absl::flat_hash_map<std::string, MyData> well_known_types_;
    well_known_types_.insert({
        {"x", x},
        {"y", y},
        {"z", z}
    });
    return 0;
}
