// Generated C++ source code from file_lists.cmake
// This file contains std::vector definitions generated from CMake 'set' commands
#include <vector>
#include <string>

// Definition for libprotobuf_srcs
std::vector<std::string> libprotobuf_srcs = {
    "./src/google/protobuf/any.pb.cc",
    "./src/google/protobuf/api.pb.cc",
    "./src/google/protobuf/duration.pb.cc",
    "./src/google/protobuf/empty.pb.cc",
    "./src/google/protobuf/field_mask.pb.cc",
    "./src/google/protobuf/source_context.pb.cc",
    "./src/google/protobuf/struct.pb.cc",
    "./src/google/protobuf/timestamp.pb.cc",
    "./src/google/protobuf/type.pb.cc",
    "./src/google/protobuf/wrappers.pb.cc",
    "./src/google/protobuf/any.cc",
    "./src/google/protobuf/any_lite.cc",
    "./src/google/protobuf/arena.cc",
    "./src/google/protobuf/arena_align.cc",
    "./src/google/protobuf/arenastring.cc",
    "./src/google/protobuf/arenaz_sampler.cc",
    "./src/google/protobuf/compiler/importer.cc",
    "./src/google/protobuf/compiler/parser.cc",
    "./src/google/protobuf/cpp_features.pb.cc",
    "./src/google/protobuf/descriptor.cc",
    "./src/google/protobuf/descriptor.pb.cc",
    "./src/google/protobuf/descriptor_database.cc",
    "./src/google/protobuf/dynamic_message.cc",
    "./src/google/protobuf/extension_set.cc",
    "./src/google/protobuf/extension_set_heavy.cc",
    "./src/google/protobuf/feature_resolver.cc",
    "./src/google/protobuf/generated_enum_util.cc",
    "./src/google/protobuf/generated_message_bases.cc",
    "./src/google/protobuf/generated_message_reflection.cc",
    "./src/google/protobuf/generated_message_tctable_full.cc",
    "./src/google/protobuf/generated_message_tctable_gen.cc",
    "./src/google/protobuf/generated_message_tctable_lite.cc",
    "./src/google/protobuf/generated_message_util.cc",
    "./src/google/protobuf/implicit_weak_message.cc",
    "./src/google/protobuf/inlined_string_field.cc",
    "./src/google/protobuf/io/coded_stream.cc",
    "./src/google/protobuf/io/gzip_stream.cc",
    "./src/google/protobuf/io/io_win32.cc",
    "./src/google/protobuf/io/printer.cc",
    "./src/google/protobuf/io/strtod.cc",
    "./src/google/protobuf/io/tokenizer.cc",
    "./src/google/protobuf/io/zero_copy_sink.cc",
    "./src/google/protobuf/io/zero_copy_stream.cc",
    "./src/google/protobuf/io/zero_copy_stream_impl.cc",
    "./src/google/protobuf/io/zero_copy_stream_impl_lite.cc",
    "./src/google/protobuf/json/internal/lexer.cc",
    "./src/google/protobuf/json/internal/message_path.cc",
    "./src/google/protobuf/json/internal/parser.cc",
    "./src/google/protobuf/json/internal/unparser.cc",
    "./src/google/protobuf/json/internal/untyped_message.cc",
    "./src/google/protobuf/json/internal/writer.cc",
    "./src/google/protobuf/json/internal/zero_copy_buffered_stream.cc",
    "./src/google/protobuf/json/json.cc",
    "./src/google/protobuf/map.cc",
    "./src/google/protobuf/map_field.cc",
    "./src/google/protobuf/message.cc",
    "./src/google/protobuf/message_lite.cc",
    "./src/google/protobuf/parse_context.cc",
    "./src/google/protobuf/port.cc",
    "./src/google/protobuf/raw_ptr.cc",
    "./src/google/protobuf/reflection_mode.cc",
    "./src/google/protobuf/reflection_ops.cc",
    "./src/google/protobuf/repeated_field.cc",
    "./src/google/protobuf/repeated_ptr_field.cc",
    "./src/google/protobuf/service.cc",
    "./src/google/protobuf/stubs/common.cc",
    "./src/google/protobuf/text_format.cc",
    "./src/google/protobuf/unknown_field_set.cc",
    "./src/google/protobuf/util/delimited_message_util.cc",
    "./src/google/protobuf/util/field_comparator.cc",
    "./src/google/protobuf/util/field_mask_util.cc",
    "./src/google/protobuf/util/message_differencer.cc",
    "./src/google/protobuf/util/time_util.cc",
    "./src/google/protobuf/util/type_resolver_util.cc",
    "./src/google/protobuf/wire_format.cc",
    "./src/google/protobuf/wire_format_lite.cc",
};

// Definition for libprotobuf_hdrs
std::vector<std::string> libprotobuf_hdrs = {
    "./src/google/protobuf/any.pb.h",
    "./src/google/protobuf/api.pb.h",
    "./src/google/protobuf/duration.pb.h",
    "./src/google/protobuf/empty.pb.h",
    "./src/google/protobuf/field_mask.pb.h",
    "./src/google/protobuf/source_context.pb.h",
    "./src/google/protobuf/struct.pb.h",
    "./src/google/protobuf/timestamp.pb.h",
    "./src/google/protobuf/type.pb.h",
    "./src/google/protobuf/wrappers.pb.h",
    "./src/google/protobuf/any.h",
    "./src/google/protobuf/arena.h",
    "./src/google/protobuf/arena_align.h",
    "./src/google/protobuf/arena_allocation_policy.h",
    "./src/google/protobuf/arena_cleanup.h",
    "./src/google/protobuf/arenastring.h",
    "./src/google/protobuf/arenaz_sampler.h",
    "./src/google/protobuf/compiler/importer.h",
    "./src/google/protobuf/compiler/parser.h",
    "./src/google/protobuf/cpp_edition_defaults.h",
    "./src/google/protobuf/cpp_features.pb.h",
    "./src/google/protobuf/descriptor.h",
    "./src/google/protobuf/descriptor.pb.h",
    "./src/google/protobuf/descriptor_database.h",
    "./src/google/protobuf/descriptor_legacy.h",
    "./src/google/protobuf/descriptor_lite.h",
    "./src/google/protobuf/descriptor_visitor.h",
    "./src/google/protobuf/dynamic_message.h",
    "./src/google/protobuf/endian.h",
    "./src/google/protobuf/explicitly_constructed.h",
    "./src/google/protobuf/extension_set.h",
    "./src/google/protobuf/extension_set_inl.h",
    "./src/google/protobuf/feature_resolver.h",
    "./src/google/protobuf/field_access_listener.h",
    "./src/google/protobuf/generated_enum_reflection.h",
    "./src/google/protobuf/generated_enum_util.h",
    "./src/google/protobuf/generated_message_bases.h",
    "./src/google/protobuf/generated_message_reflection.h",
    "./src/google/protobuf/generated_message_tctable_decl.h",
    "./src/google/protobuf/generated_message_tctable_gen.h",
    "./src/google/protobuf/generated_message_tctable_impl.h",
    "./src/google/protobuf/generated_message_util.h",
    "./src/google/protobuf/has_bits.h",
    "./src/google/protobuf/implicit_weak_message.h",
    "./src/google/protobuf/inlined_string_field.h",
    "./src/google/protobuf/internal_visibility.h",
    "./src/google/protobuf/io/coded_stream.h",
    "./src/google/protobuf/io/gzip_stream.h",
    "./src/google/protobuf/io/io_win32.h",
    "./src/google/protobuf/io/printer.h",
    "./src/google/protobuf/io/strtod.h",
    "./src/google/protobuf/io/tokenizer.h",
    "./src/google/protobuf/io/zero_copy_sink.h",
    "./src/google/protobuf/io/zero_copy_stream.h",
    "./src/google/protobuf/io/zero_copy_stream_impl.h",
    "./src/google/protobuf/io/zero_copy_stream_impl_lite.h",
    "./src/google/protobuf/json/internal/descriptor_traits.h",
    "./src/google/protobuf/json/internal/lexer.h",
    "./src/google/protobuf/json/internal/message_path.h",
    "./src/google/protobuf/json/internal/parser.h",
    "./src/google/protobuf/json/internal/parser_traits.h",
    "./src/google/protobuf/json/internal/unparser.h",
    "./src/google/protobuf/json/internal/unparser_traits.h",
    "./src/google/protobuf/json/internal/untyped_message.h",
    "./src/google/protobuf/json/internal/writer.h",
    "./src/google/protobuf/json/internal/zero_copy_buffered_stream.h",
    "./src/google/protobuf/json/json.h",
    "./src/google/protobuf/map.h",
    "./src/google/protobuf/map_entry.h",
    "./src/google/protobuf/map_field.h",
    "./src/google/protobuf/map_field_inl.h",
    "./src/google/protobuf/map_field_lite.h",
    "./src/google/protobuf/map_type_handler.h",
    "./src/google/protobuf/message.h",
    "./src/google/protobuf/message_lite.h",
    "./src/google/protobuf/metadata.h",
    "./src/google/protobuf/metadata_lite.h",
    "./src/google/protobuf/parse_context.h",
    "./src/google/protobuf/port.h",
    "./src/google/protobuf/port_def.inc",
    "./src/google/protobuf/port_undef.inc",
    "./src/google/protobuf/raw_ptr.h",
    "./src/google/protobuf/reflection.h",
    "./src/google/protobuf/reflection_internal.h",
    "./src/google/protobuf/reflection_mode.h",
    "./src/google/protobuf/reflection_ops.h",
    "./src/google/protobuf/reflection_visit_field_info.h",
    "./src/google/protobuf/reflection_visit_fields.h",
    "./src/google/protobuf/repeated_field.h",
    "./src/google/protobuf/repeated_ptr_field.h",
    "./src/google/protobuf/runtime_version.h",
    "./src/google/protobuf/serial_arena.h",
    "./src/google/protobuf/service.h",
    "./src/google/protobuf/string_block.h",
    "./src/google/protobuf/stubs/callback.h",
    "./src/google/protobuf/stubs/common.h",
    "./src/google/protobuf/stubs/platform_macros.h",
    "./src/google/protobuf/stubs/port.h",
    "./src/google/protobuf/stubs/status_macros.h",
    "./src/google/protobuf/text_format.h",
    "./src/google/protobuf/thread_safe_arena.h",
    "./src/google/protobuf/unknown_field_set.h",
    "./src/google/protobuf/util/delimited_message_util.h",
    "./src/google/protobuf/util/field_comparator.h",
    "./src/google/protobuf/util/field_mask_util.h",
    "./src/google/protobuf/util/json_util.h",
    "./src/google/protobuf/util/message_differencer.h",
    "./src/google/protobuf/util/time_util.h",
    "./src/google/protobuf/util/type_resolver.h",
    "./src/google/protobuf/util/type_resolver_util.h",
    "./src/google/protobuf/varint_shuffle.h",
    "./src/google/protobuf/wire_format.h",
    "./src/google/protobuf/wire_format_lite.h",
};

// Definition for libprotobuf_lite_srcs
std::vector<std::string> libprotobuf_lite_srcs = {
    "./src/google/protobuf/any_lite.cc",
    "./src/google/protobuf/arena.cc",
    "./src/google/protobuf/arena_align.cc",
    "./src/google/protobuf/arenastring.cc",
    "./src/google/protobuf/arenaz_sampler.cc",
    "./src/google/protobuf/extension_set.cc",
    "./src/google/protobuf/generated_enum_util.cc",
    "./src/google/protobuf/generated_message_tctable_lite.cc",
    "./src/google/protobuf/generated_message_util.cc",
    "./src/google/protobuf/implicit_weak_message.cc",
    "./src/google/protobuf/inlined_string_field.cc",
    "./src/google/protobuf/io/coded_stream.cc",
    "./src/google/protobuf/io/io_win32.cc",
    "./src/google/protobuf/io/zero_copy_stream.cc",
    "./src/google/protobuf/io/zero_copy_stream_impl.cc",
    "./src/google/protobuf/io/zero_copy_stream_impl_lite.cc",
    "./src/google/protobuf/map.cc",
    "./src/google/protobuf/message_lite.cc",
    "./src/google/protobuf/parse_context.cc",
    "./src/google/protobuf/port.cc",
    "./src/google/protobuf/raw_ptr.cc",
    "./src/google/protobuf/repeated_field.cc",
    "./src/google/protobuf/repeated_ptr_field.cc",
    "./src/google/protobuf/stubs/common.cc",
    "./src/google/protobuf/wire_format_lite.cc",
};

// Definition for libprotobuf_lite_hdrs
std::vector<std::string> libprotobuf_lite_hdrs = {
    "./src/google/protobuf/any.h",
    "./src/google/protobuf/arena.h",
    "./src/google/protobuf/arena_align.h",
    "./src/google/protobuf/arena_allocation_policy.h",
    "./src/google/protobuf/arena_cleanup.h",
    "./src/google/protobuf/arenastring.h",
    "./src/google/protobuf/arenaz_sampler.h",
    "./src/google/protobuf/descriptor_lite.h",
    "./src/google/protobuf/endian.h",
    "./src/google/protobuf/explicitly_constructed.h",
    "./src/google/protobuf/extension_set.h",
    "./src/google/protobuf/extension_set_inl.h",
    "./src/google/protobuf/generated_enum_util.h",
    "./src/google/protobuf/generated_message_tctable_decl.h",
    "./src/google/protobuf/generated_message_tctable_impl.h",
    "./src/google/protobuf/generated_message_util.h",
    "./src/google/protobuf/has_bits.h",
    "./src/google/protobuf/implicit_weak_message.h",
    "./src/google/protobuf/inlined_string_field.h",
    "./src/google/protobuf/internal_visibility.h",
    "./src/google/protobuf/io/coded_stream.h",
    "./src/google/protobuf/io/io_win32.h",
    "./src/google/protobuf/io/zero_copy_stream.h",
    "./src/google/protobuf/io/zero_copy_stream_impl.h",
    "./src/google/protobuf/io/zero_copy_stream_impl_lite.h",
    "./src/google/protobuf/map.h",
    "./src/google/protobuf/map_field_lite.h",
    "./src/google/protobuf/map_type_handler.h",
    "./src/google/protobuf/message_lite.h",
    "./src/google/protobuf/metadata_lite.h",
    "./src/google/protobuf/parse_context.h",
    "./src/google/protobuf/port.h",
    "./src/google/protobuf/port_def.inc",
    "./src/google/protobuf/port_undef.inc",
    "./src/google/protobuf/raw_ptr.h",
    "./src/google/protobuf/repeated_field.h",
    "./src/google/protobuf/repeated_ptr_field.h",
    "./src/google/protobuf/runtime_version.h",
    "./src/google/protobuf/serial_arena.h",
    "./src/google/protobuf/string_block.h",
    "./src/google/protobuf/stubs/callback.h",
    "./src/google/protobuf/stubs/common.h",
    "./src/google/protobuf/stubs/platform_macros.h",
    "./src/google/protobuf/stubs/port.h",
    "./src/google/protobuf/stubs/status_macros.h",
    "./src/google/protobuf/thread_safe_arena.h",
    "./src/google/protobuf/varint_shuffle.h",
    "./src/google/protobuf/wire_format_lite.h",
};

// Definition for libprotoc_srcs
std::vector<std::string> libprotoc_srcs = {
    "./src/google/protobuf/compiler/code_generator.cc",
    "./src/google/protobuf/compiler/code_generator_lite.cc",
    "./src/google/protobuf/compiler/command_line_interface.cc",
    "./src/google/protobuf/compiler/cpp/enum.cc",
    "./src/google/protobuf/compiler/cpp/extension.cc",
    "./src/google/protobuf/compiler/cpp/field.cc",
    "./src/google/protobuf/compiler/cpp/field_generators/cord_field.cc",
    "./src/google/protobuf/compiler/cpp/field_generators/enum_field.cc",
    "./src/google/protobuf/compiler/cpp/field_generators/map_field.cc",
    "./src/google/protobuf/compiler/cpp/field_generators/message_field.cc",
    "./src/google/protobuf/compiler/cpp/field_generators/primitive_field.cc",
    "./src/google/protobuf/compiler/cpp/field_generators/string_field.cc",
    "./src/google/protobuf/compiler/cpp/field_generators/string_view_field.cc",
    "./src/google/protobuf/compiler/cpp/file.cc",
    "./src/google/protobuf/compiler/cpp/generator.cc",
    "./src/google/protobuf/compiler/cpp/helpers.cc",
    "./src/google/protobuf/compiler/cpp/ifndef_guard.cc",
    "./src/google/protobuf/compiler/cpp/message.cc",
    "./src/google/protobuf/compiler/cpp/namespace_printer.cc",
    "./src/google/protobuf/compiler/cpp/padding_optimizer.cc",
    "./src/google/protobuf/compiler/cpp/parse_function_generator.cc",
    "./src/google/protobuf/compiler/cpp/service.cc",
    "./src/google/protobuf/compiler/cpp/tracker.cc",
    "./src/google/protobuf/compiler/csharp/csharp_doc_comment.cc",
    "./src/google/protobuf/compiler/csharp/csharp_enum.cc",
    "./src/google/protobuf/compiler/csharp/csharp_enum_field.cc",
    "./src/google/protobuf/compiler/csharp/csharp_field_base.cc",
    "./src/google/protobuf/compiler/csharp/csharp_generator.cc",
    "./src/google/protobuf/compiler/csharp/csharp_helpers.cc",
    "./src/google/protobuf/compiler/csharp/csharp_map_field.cc",
    "./src/google/protobuf/compiler/csharp/csharp_message.cc",
    "./src/google/protobuf/compiler/csharp/csharp_message_field.cc",
    "./src/google/protobuf/compiler/csharp/csharp_primitive_field.cc",
    "./src/google/protobuf/compiler/csharp/csharp_reflection_class.cc",
    "./src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.cc",
    "./src/google/protobuf/compiler/csharp/csharp_repeated_message_field.cc",
    "./src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.cc",
    "./src/google/protobuf/compiler/csharp/csharp_source_generator_base.cc",
    "./src/google/protobuf/compiler/csharp/csharp_wrapper_field.cc",
    "./src/google/protobuf/compiler/csharp/names.cc",
    "./src/google/protobuf/compiler/java/context.cc",
    "./src/google/protobuf/compiler/java/doc_comment.cc",
    "./src/google/protobuf/compiler/java/field_common.cc",
    "./src/google/protobuf/compiler/java/file.cc",
    "./src/google/protobuf/compiler/java/full/enum.cc",
    "./src/google/protobuf/compiler/java/full/enum_field.cc",
    "./src/google/protobuf/compiler/java/full/extension.cc",
    "./src/google/protobuf/compiler/java/full/generator_factory.cc",
    "./src/google/protobuf/compiler/java/full/make_field_gens.cc",
    "./src/google/protobuf/compiler/java/full/map_field.cc",
    "./src/google/protobuf/compiler/java/full/message.cc",
    "./src/google/protobuf/compiler/java/full/message_builder.cc",
    "./src/google/protobuf/compiler/java/full/message_field.cc",
    "./src/google/protobuf/compiler/java/full/primitive_field.cc",
    "./src/google/protobuf/compiler/java/full/service.cc",
    "./src/google/protobuf/compiler/java/full/string_field.cc",
    "./src/google/protobuf/compiler/java/generator.cc",
    "./src/google/protobuf/compiler/java/helpers.cc",
    "./src/google/protobuf/compiler/java/internal_helpers.cc",
    "./src/google/protobuf/compiler/java/java_features.pb.cc",
    "./src/google/protobuf/compiler/java/lite/enum.cc",
    "./src/google/protobuf/compiler/java/lite/enum_field.cc",
    "./src/google/protobuf/compiler/java/lite/extension.cc",
    "./src/google/protobuf/compiler/java/lite/generator_factory.cc",
    "./src/google/protobuf/compiler/java/lite/make_field_gens.cc",
    "./src/google/protobuf/compiler/java/lite/map_field.cc",
    "./src/google/protobuf/compiler/java/lite/message.cc",
    "./src/google/protobuf/compiler/java/lite/message_builder.cc",
    "./src/google/protobuf/compiler/java/lite/message_field.cc",
    "./src/google/protobuf/compiler/java/lite/primitive_field.cc",
    "./src/google/protobuf/compiler/java/lite/string_field.cc",
    "./src/google/protobuf/compiler/java/message_serialization.cc",
    "./src/google/protobuf/compiler/java/name_resolver.cc",
    "./src/google/protobuf/compiler/java/names.cc",
    "./src/google/protobuf/compiler/java/shared_code_generator.cc",
    "./src/google/protobuf/compiler/kotlin/file.cc",
    "./src/google/protobuf/compiler/kotlin/generator.cc",
    "./src/google/protobuf/compiler/kotlin/message.cc",
    "./src/google/protobuf/compiler/objectivec/enum.cc",
    "./src/google/protobuf/compiler/objectivec/enum_field.cc",
    "./src/google/protobuf/compiler/objectivec/extension.cc",
    "./src/google/protobuf/compiler/objectivec/field.cc",
    "./src/google/protobuf/compiler/objectivec/file.cc",
    "./src/google/protobuf/compiler/objectivec/generator.cc",
    "./src/google/protobuf/compiler/objectivec/helpers.cc",
    "./src/google/protobuf/compiler/objectivec/import_writer.cc",
    "./src/google/protobuf/compiler/objectivec/line_consumer.cc",
    "./src/google/protobuf/compiler/objectivec/map_field.cc",
    "./src/google/protobuf/compiler/objectivec/message.cc",
    "./src/google/protobuf/compiler/objectivec/message_field.cc",
    "./src/google/protobuf/compiler/objectivec/names.cc",
    "./src/google/protobuf/compiler/objectivec/oneof.cc",
    "./src/google/protobuf/compiler/objectivec/primitive_field.cc",
    "./src/google/protobuf/compiler/objectivec/tf_decode_data.cc",
    "./src/google/protobuf/compiler/php/names.cc",
    "./src/google/protobuf/compiler/php/php_generator.cc",
    "./src/google/protobuf/compiler/plugin.cc",
    "./src/google/protobuf/compiler/plugin.pb.cc",
    "./src/google/protobuf/compiler/python/generator.cc",
    "./src/google/protobuf/compiler/python/helpers.cc",
    "./src/google/protobuf/compiler/python/pyi_generator.cc",
    "./src/google/protobuf/compiler/retention.cc",
    "./src/google/protobuf/compiler/ruby/ruby_generator.cc",
    "./src/google/protobuf/compiler/rust/accessors/accessor_case.cc",
    "./src/google/protobuf/compiler/rust/accessors/accessors.cc",
    "./src/google/protobuf/compiler/rust/accessors/default_value.cc",
    "./src/google/protobuf/compiler/rust/accessors/map.cc",
    "./src/google/protobuf/compiler/rust/accessors/repeated_field.cc",
    "./src/google/protobuf/compiler/rust/accessors/singular_cord.cc",
    "./src/google/protobuf/compiler/rust/accessors/singular_message.cc",
    "./src/google/protobuf/compiler/rust/accessors/singular_scalar.cc",
    "./src/google/protobuf/compiler/rust/accessors/singular_string.cc",
    "./src/google/protobuf/compiler/rust/accessors/unsupported_field.cc",
    "./src/google/protobuf/compiler/rust/accessors/with_presence.cc",
    "./src/google/protobuf/compiler/rust/context.cc",
    "./src/google/protobuf/compiler/rust/crate_mapping.cc",
    "./src/google/protobuf/compiler/rust/enum.cc",
    "./src/google/protobuf/compiler/rust/generator.cc",
    "./src/google/protobuf/compiler/rust/message.cc",
    "./src/google/protobuf/compiler/rust/naming.cc",
    "./src/google/protobuf/compiler/rust/oneof.cc",
    "./src/google/protobuf/compiler/rust/relative_path.cc",
    "./src/google/protobuf/compiler/rust/rust_field_type.cc",
    "./src/google/protobuf/compiler/rust/rust_keywords.cc",
    "./src/google/protobuf/compiler/rust/upb_helpers.cc",
    "./src/google/protobuf/compiler/subprocess.cc",
    "./src/google/protobuf/compiler/versions.cc",
    "./src/google/protobuf/compiler/zip_writer.cc",
    "./src/google/protobuf/testing/file.cc",
    "./upb_generator/common/names.cc",
    "./upb_generator/minitable/names.cc",
    "./upb_generator/minitable/names_internal.cc",
};

// Definition for libprotoc_hdrs
std::vector<std::string> libprotoc_hdrs = {
    "./src/google/protobuf/compiler/code_generator.h",
    "./src/google/protobuf/compiler/code_generator_lite.h",
    "./src/google/protobuf/compiler/command_line_interface.h",
    "./src/google/protobuf/compiler/cpp/enum.h",
    "./src/google/protobuf/compiler/cpp/extension.h",
    "./src/google/protobuf/compiler/cpp/field.h",
    "./src/google/protobuf/compiler/cpp/field_generators/generators.h",
    "./src/google/protobuf/compiler/cpp/file.h",
    "./src/google/protobuf/compiler/cpp/generator.h",
    "./src/google/protobuf/compiler/cpp/helpers.h",
    "./src/google/protobuf/compiler/cpp/ifndef_guard.h",
    "./src/google/protobuf/compiler/cpp/message.h",
    "./src/google/protobuf/compiler/cpp/message_layout_helper.h",
    "./src/google/protobuf/compiler/cpp/names.h",
    "./src/google/protobuf/compiler/cpp/namespace_printer.h",
    "./src/google/protobuf/compiler/cpp/options.h",
    "./src/google/protobuf/compiler/cpp/padding_optimizer.h",
    "./src/google/protobuf/compiler/cpp/parse_function_generator.h",
    "./src/google/protobuf/compiler/cpp/service.h",
    "./src/google/protobuf/compiler/cpp/tracker.h",
    "./src/google/protobuf/compiler/csharp/csharp_doc_comment.h",
    "./src/google/protobuf/compiler/csharp/csharp_enum.h",
    "./src/google/protobuf/compiler/csharp/csharp_enum_field.h",
    "./src/google/protobuf/compiler/csharp/csharp_field_base.h",
    "./src/google/protobuf/compiler/csharp/csharp_generator.h",
    "./src/google/protobuf/compiler/csharp/csharp_helpers.h",
    "./src/google/protobuf/compiler/csharp/csharp_map_field.h",
    "./src/google/protobuf/compiler/csharp/csharp_message.h",
    "./src/google/protobuf/compiler/csharp/csharp_message_field.h",
    "./src/google/protobuf/compiler/csharp/csharp_options.h",
    "./src/google/protobuf/compiler/csharp/csharp_primitive_field.h",
    "./src/google/protobuf/compiler/csharp/csharp_reflection_class.h",
    "./src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h",
    "./src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h",
    "./src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h",
    "./src/google/protobuf/compiler/csharp/csharp_source_generator_base.h",
    "./src/google/protobuf/compiler/csharp/csharp_wrapper_field.h",
    "./src/google/protobuf/compiler/csharp/names.h",
    "./src/google/protobuf/compiler/java/context.h",
    "./src/google/protobuf/compiler/java/doc_comment.h",
    "./src/google/protobuf/compiler/java/field_common.h",
    "./src/google/protobuf/compiler/java/file.h",
    "./src/google/protobuf/compiler/java/full/enum.h",
    "./src/google/protobuf/compiler/java/full/enum_field.h",
    "./src/google/protobuf/compiler/java/full/extension.h",
    "./src/google/protobuf/compiler/java/full/field_generator.h",
    "./src/google/protobuf/compiler/java/full/generator_factory.h",
    "./src/google/protobuf/compiler/java/full/make_field_gens.h",
    "./src/google/protobuf/compiler/java/full/map_field.h",
    "./src/google/protobuf/compiler/java/full/message.h",
    "./src/google/protobuf/compiler/java/full/message_builder.h",
    "./src/google/protobuf/compiler/java/full/message_field.h",
    "./src/google/protobuf/compiler/java/full/primitive_field.h",
    "./src/google/protobuf/compiler/java/full/service.h",
    "./src/google/protobuf/compiler/java/full/string_field.h",
    "./src/google/protobuf/compiler/java/generator.h",
    "./src/google/protobuf/compiler/java/generator_common.h",
    "./src/google/protobuf/compiler/java/generator_factory.h",
    "./src/google/protobuf/compiler/java/helpers.h",
    "./src/google/protobuf/compiler/java/internal_helpers.h",
    "./src/google/protobuf/compiler/java/java_features.pb.h",
    "./src/google/protobuf/compiler/java/lite/enum.h",
    "./src/google/protobuf/compiler/java/lite/enum_field.h",
    "./src/google/protobuf/compiler/java/lite/extension.h",
    "./src/google/protobuf/compiler/java/lite/field_generator.h",
    "./src/google/protobuf/compiler/java/lite/generator_factory.h",
    "./src/google/protobuf/compiler/java/lite/make_field_gens.h",
    "./src/google/protobuf/compiler/java/lite/map_field.h",
    "./src/google/protobuf/compiler/java/lite/message.h",
    "./src/google/protobuf/compiler/java/lite/message_builder.h",
    "./src/google/protobuf/compiler/java/lite/message_field.h",
    "./src/google/protobuf/compiler/java/lite/primitive_field.h",
    "./src/google/protobuf/compiler/java/lite/string_field.h",
    "./src/google/protobuf/compiler/java/message_serialization.h",
    "./src/google/protobuf/compiler/java/name_resolver.h",
    "./src/google/protobuf/compiler/java/names.h",
    "./src/google/protobuf/compiler/java/options.h",
    "./src/google/protobuf/compiler/java/shared_code_generator.h",
    "./src/google/protobuf/compiler/kotlin/file.h",
    "./src/google/protobuf/compiler/kotlin/generator.h",
    "./src/google/protobuf/compiler/kotlin/message.h",
    "./src/google/protobuf/compiler/objectivec/enum.h",
    "./src/google/protobuf/compiler/objectivec/enum_field.h",
    "./src/google/protobuf/compiler/objectivec/extension.h",
    "./src/google/protobuf/compiler/objectivec/field.h",
    "./src/google/protobuf/compiler/objectivec/file.h",
    "./src/google/protobuf/compiler/objectivec/generator.h",
    "./src/google/protobuf/compiler/objectivec/helpers.h",
    "./src/google/protobuf/compiler/objectivec/import_writer.h",
    "./src/google/protobuf/compiler/objectivec/line_consumer.h",
    "./src/google/protobuf/compiler/objectivec/map_field.h",
    "./src/google/protobuf/compiler/objectivec/message.h",
    "./src/google/protobuf/compiler/objectivec/message_field.h",
    "./src/google/protobuf/compiler/objectivec/names.h",
    "./src/google/protobuf/compiler/objectivec/nsobject_methods.h",
    "./src/google/protobuf/compiler/objectivec/oneof.h",
    "./src/google/protobuf/compiler/objectivec/options.h",
    "./src/google/protobuf/compiler/objectivec/primitive_field.h",
    "./src/google/protobuf/compiler/objectivec/tf_decode_data.h",
    "./src/google/protobuf/compiler/php/names.h",
    "./src/google/protobuf/compiler/php/php_generator.h",
    "./src/google/protobuf/compiler/plugin.h",
    "./src/google/protobuf/compiler/plugin.pb.h",
    "./src/google/protobuf/compiler/python/generator.h",
    "./src/google/protobuf/compiler/python/helpers.h",
    "./src/google/protobuf/compiler/python/pyi_generator.h",
    "./src/google/protobuf/compiler/retention.h",
    "./src/google/protobuf/compiler/ruby/ruby_generator.h",
    "./src/google/protobuf/compiler/rust/accessors/accessor_case.h",
    "./src/google/protobuf/compiler/rust/accessors/accessors.h",
    "./src/google/protobuf/compiler/rust/accessors/default_value.h",
    "./src/google/protobuf/compiler/rust/accessors/generator.h",
    "./src/google/protobuf/compiler/rust/accessors/with_presence.h",
    "./src/google/protobuf/compiler/rust/context.h",
    "./src/google/protobuf/compiler/rust/crate_mapping.h",
    "./src/google/protobuf/compiler/rust/enum.h",
    "./src/google/protobuf/compiler/rust/generator.h",
    "./src/google/protobuf/compiler/rust/message.h",
    "./src/google/protobuf/compiler/rust/naming.h",
    "./src/google/protobuf/compiler/rust/oneof.h",
    "./src/google/protobuf/compiler/rust/relative_path.h",
    "./src/google/protobuf/compiler/rust/rust_field_type.h",
    "./src/google/protobuf/compiler/rust/rust_keywords.h",
    "./src/google/protobuf/compiler/rust/upb_helpers.h",
    "./src/google/protobuf/compiler/scc.h",
    "./src/google/protobuf/compiler/subprocess.h",
    "./src/google/protobuf/compiler/versions.h",
    "./src/google/protobuf/compiler/zip_writer.h",
    "./src/google/protobuf/testing/file.h",
    "./upb/port/atomic.h",
    "./upb/port/def.inc",
    "./upb/port/undef.inc",
    "./upb/port/vsnprintf_compat.h",
    "./upb_generator/common/names.h",
    "./upb_generator/minitable/names.h",
    "./upb_generator/minitable/names_internal.h",
};

// Definition for libupb_srcs
std::vector<std::string> libupb_srcs = {
    "./upb/base/status.c",
    "./upb/hash/common.c",
    "./upb/json/decode.c",
    "./upb/json/encode.c",
    "./upb/lex/atoi.c",
    "./upb/lex/round_trip.c",
    "./upb/lex/strtod.c",
    "./upb/lex/unicode.c",
    "./upb/mem/alloc.c",
    "./upb/mem/arena.c",
    "./upb/message/accessors.c",
    "./upb/message/array.c",
    "./upb/message/compare.c",
    "./upb/message/compat.c",
    "./upb/message/copy.c",
    "./upb/message/internal/compare_unknown.c",
    "./upb/message/internal/extension.c",
    "./upb/message/internal/iterator.c",
    "./upb/message/internal/message.c",
    "./upb/message/map.c",
    "./upb/message/map_sorter.c",
    "./upb/message/merge.c",
    "./upb/message/message.c",
    "./upb/mini_descriptor/build_enum.c",
    "./upb/mini_descriptor/decode.c",
    "./upb/mini_descriptor/internal/base92.c",
    "./upb/mini_descriptor/internal/encode.c",
    "./upb/mini_descriptor/link.c",
    "./upb/mini_table/extension_registry.c",
    "./upb/mini_table/internal/message.c",
    "./upb/mini_table/message.c",
    "./upb/reflection/def_pool.c",
    "./upb/reflection/def_type.c",
    "./upb/reflection/desc_state.c",
    "./upb/reflection/enum_def.c",
    "./upb/reflection/enum_reserved_range.c",
    "./upb/reflection/enum_value_def.c",
    "./upb/reflection/extension_range.c",
    "./upb/reflection/field_def.c",
    "./upb/reflection/file_def.c",
    "./upb/reflection/internal/def_builder.c",
    "./upb/reflection/internal/strdup2.c",
    "./upb/reflection/message.c",
    "./upb/reflection/message_def.c",
    "./upb/reflection/message_reserved_range.c",
    "./upb/reflection/method_def.c",
    "./upb/reflection/oneof_def.c",
    "./upb/reflection/service_def.c",
    "./upb/text/encode.c",
    "./upb/text/internal/encode.c",
    "./upb/util/def_to_proto.c",
    "./upb/util/required_fields.c",
    "./upb/wire/byte_size.c",
    "./upb/wire/decode.c",
    "./upb/wire/encode.c",
    "./upb/wire/eps_copy_input_stream.c",
    "./upb/wire/internal/decode_fast.c",
    "./upb/wire/reader.c",
};

// Definition for libupb_hdrs
std::vector<std::string> libupb_hdrs = {
    "./upb/base/descriptor_constants.h",
    "./upb/base/internal/endian.h",
    "./upb/base/internal/log2.h",
    "./upb/base/status.h",
    "./upb/base/status.hpp",
    "./upb/base/string_view.h",
    "./upb/base/upcast.h",
    "./upb/generated_code_support.h",
    "./upb/hash/common.h",
    "./upb/hash/int_table.h",
    "./upb/hash/str_table.h",
    "./upb/json/decode.h",
    "./upb/json/encode.h",
    "./upb/lex/atoi.h",
    "./upb/lex/round_trip.h",
    "./upb/lex/strtod.h",
    "./upb/lex/unicode.h",
    "./upb/mem/alloc.h",
    "./upb/mem/arena.h",
    "./upb/mem/arena.hpp",
    "./upb/mem/internal/arena.h",
    "./upb/message/accessors.h",
    "./upb/message/array.h",
    "./upb/message/compare.h",
    "./upb/message/compat.h",
    "./upb/message/copy.h",
    "./upb/message/internal/accessors.h",
    "./upb/message/internal/array.h",
    "./upb/message/internal/compare_unknown.h",
    "./upb/message/internal/extension.h",
    "./upb/message/internal/iterator.h",
    "./upb/message/internal/map.h",
    "./upb/message/internal/map_entry.h",
    "./upb/message/internal/map_sorter.h",
    "./upb/message/internal/message.h",
    "./upb/message/internal/tagged_ptr.h",
    "./upb/message/internal/types.h",
    "./upb/message/map.h",
    "./upb/message/map_gencode_util.h",
    "./upb/message/merge.h",
    "./upb/message/message.h",
    "./upb/message/tagged_ptr.h",
    "./upb/message/value.h",
    "./upb/mini_descriptor/build_enum.h",
    "./upb/mini_descriptor/decode.h",
    "./upb/mini_descriptor/internal/base92.h",
    "./upb/mini_descriptor/internal/decoder.h",
    "./upb/mini_descriptor/internal/encode.h",
    "./upb/mini_descriptor/internal/encode.hpp",
    "./upb/mini_descriptor/internal/modifiers.h",
    "./upb/mini_descriptor/internal/wire_constants.h",
    "./upb/mini_descriptor/link.h",
    "./upb/mini_table/enum.h",
    "./upb/mini_table/extension.h",
    "./upb/mini_table/extension_registry.h",
    "./upb/mini_table/field.h",
    "./upb/mini_table/file.h",
    "./upb/mini_table/internal/enum.h",
    "./upb/mini_table/internal/extension.h",
    "./upb/mini_table/internal/field.h",
    "./upb/mini_table/internal/file.h",
    "./upb/mini_table/internal/message.h",
    "./upb/mini_table/internal/size_log2.h",
    "./upb/mini_table/internal/sub.h",
    "./upb/mini_table/message.h",
    "./upb/mini_table/sub.h",
    "./upb/port/atomic.h",
    "./upb/port/def.inc",
    "./upb/port/undef.inc",
    "./upb/port/vsnprintf_compat.h",
    "./upb/reflection/common.h",
    "./upb/reflection/def.h",
    "./upb/reflection/def.hpp",
    "./upb/reflection/def_pool.h",
    "./upb/reflection/def_type.h",
    "./upb/reflection/descriptor_bootstrap.h",
    "./upb/reflection/enum_def.h",
    "./upb/reflection/enum_reserved_range.h",
    "./upb/reflection/enum_value_def.h",
    "./upb/reflection/extension_range.h",
    "./upb/reflection/field_def.h",
    "./upb/reflection/file_def.h",
    "./upb/reflection/internal/def_pool.h",
    "./upb/reflection/internal/desc_state.h",
    "./upb/reflection/internal/enum_def.h",
    "./upb/reflection/internal/enum_reserved_range.h",
    "./upb/reflection/internal/enum_value_def.h",
    "./upb/reflection/internal/extension_range.h",
    "./upb/reflection/internal/field_def.h",
    "./upb/reflection/internal/file_def.h",
    "./upb/reflection/internal/message_def.h",
    "./upb/reflection/internal/message_reserved_range.h",
    "./upb/reflection/internal/method_def.h",
    "./upb/reflection/internal/oneof_def.h",
    "./upb/reflection/internal/service_def.h",
    "./upb/reflection/internal/upb_edition_defaults.h",
    "./upb/reflection/message.h",
    "./upb/reflection/message.hpp",
    "./upb/reflection/message_def.h",
    "./upb/reflection/message_reserved_range.h",
    "./upb/reflection/method_def.h",
    "./upb/reflection/oneof_def.h",
    "./upb/reflection/service_def.h",
    "./upb/text/encode.h",
    "./upb/text/internal/encode.h",
    "./upb/text/options.h",
    "./upb/util/def_to_proto.h",
    "./upb/util/required_fields.h",
    "./upb/wire/byte_size.h",
    "./upb/wire/decode.h",
    "./upb/wire/encode.h",
    "./upb/wire/eps_copy_input_stream.h",
    "./upb/wire/internal/decode_fast.h",
    "./upb/wire/reader.h",
    "./upb/wire/types.h",
};

// Definition for protoc_gen_upb_srcs
std::vector<std::string> protoc_gen_upb_srcs = {
    "./src/google/protobuf/compiler/code_generator_lite.cc",
    "./src/google/protobuf/port.cc",
    "./upb_generator/c/generator.cc",
    "./upb_generator/c/names.cc",
    "./upb_generator/c/names_internal.cc",
    "./upb_generator/common.cc",
    "./upb_generator/common/names.cc",
    "./upb_generator/file_layout.cc",
    "./upb_generator/minitable/names.cc",
    "./upb_generator/minitable/names_internal.cc",
};

// Definition for protoc_gen_upb_hdrs
std::vector<std::string> protoc_gen_upb_hdrs = {
    "./src/google/protobuf/compiler/code_generator_lite.h",
    "./src/google/protobuf/port.h",
    "./src/google/protobuf/port_def.inc",
    "./src/google/protobuf/port_undef.inc",
    "./upb_generator/c/names.h",
    "./upb_generator/c/names_internal.h",
    "./upb_generator/common.h",
    "./upb_generator/common/names.h",
    "./upb_generator/file_layout.h",
    "./upb_generator/minitable/names.h",
    "./upb_generator/minitable/names_internal.h",
    "./upb_generator/plugin.h",
    "./upb_generator/plugin_bootstrap.h",
};

// Definition for protoc_gen_upbdefs_srcs
std::vector<std::string> protoc_gen_upbdefs_srcs = {
    "./src/google/protobuf/compiler/code_generator_lite.cc",
    "./src/google/protobuf/port.cc",
    "./upb_generator/common.cc",
    "./upb_generator/common/names.cc",
    "./upb_generator/file_layout.cc",
    "./upb_generator/minitable/names.cc",
    "./upb_generator/minitable/names_internal.cc",
    "./upb_generator/reflection/generator.cc",
    "./upb_generator/reflection/names.cc",
};

// Definition for protoc_gen_upbdefs_hdrs
std::vector<std::string> protoc_gen_upbdefs_hdrs = {
    "./src/google/protobuf/compiler/code_generator_lite.h",
    "./src/google/protobuf/port.h",
    "./src/google/protobuf/port_def.inc",
    "./src/google/protobuf/port_undef.inc",
    "./upb_generator/common.h",
    "./upb_generator/common/names.h",
    "./upb_generator/file_layout.h",
    "./upb_generator/minitable/names.h",
    "./upb_generator/minitable/names_internal.h",
    "./upb_generator/plugin.h",
    "./upb_generator/plugin_bootstrap.h",
    "./upb_generator/reflection/names.h",
};

// Definition for protoc_gen_upb_minitable_srcs
std::vector<std::string> protoc_gen_upb_minitable_srcs = {
    "./src/google/protobuf/compiler/code_generator_lite.cc",
    "./src/google/protobuf/port.cc",
    "./upb_generator/common.cc",
    "./upb_generator/common/names.cc",
    "./upb_generator/file_layout.cc",
    "./upb_generator/minitable/fasttable.cc",
    "./upb_generator/minitable/generator.cc",
    "./upb_generator/minitable/main.cc",
    "./upb_generator/minitable/names.cc",
    "./upb_generator/minitable/names_internal.cc",
};

// Definition for protoc_gen_upb_minitable_hdrs
std::vector<std::string> protoc_gen_upb_minitable_hdrs = {
    "./src/google/protobuf/compiler/code_generator_lite.h",
    "./src/google/protobuf/port.h",
    "./src/google/protobuf/port_def.inc",
    "./src/google/protobuf/port_undef.inc",
    "./upb_generator/common.h",
    "./upb_generator/common/names.h",
    "./upb_generator/file_layout.h",
    "./upb_generator/minitable/generator.h",
    "./upb_generator/minitable/names.h",
    "./upb_generator/minitable/names_internal.h",
    "./upb_generator/plugin.h",
    "./upb_generator/plugin_bootstrap.h",
};

// Definition for wkt_protos_files
std::vector<std::string> wkt_protos_files = {
    "./src/google/protobuf/any.proto",
    "./src/google/protobuf/api.proto",
    "./src/google/protobuf/duration.proto",
    "./src/google/protobuf/empty.proto",
    "./src/google/protobuf/field_mask.proto",
    "./src/google/protobuf/source_context.proto",
    "./src/google/protobuf/struct.proto",
    "./src/google/protobuf/timestamp.proto",
    "./src/google/protobuf/type.proto",
    "./src/google/protobuf/wrappers.proto",
};

// Definition for cpp_features_proto_proto_srcs
std::vector<std::string> cpp_features_proto_proto_srcs = {
    "./src/google/protobuf/cpp_features.proto",
};

// Definition for cpp_features_proto_srcs
std::vector<std::string> cpp_features_proto_srcs = {
    "./src/google/protobuf/cpp_features.proto.pb.cc",
};

// Definition for cpp_features_proto_hdrs
std::vector<std::string> cpp_features_proto_hdrs = {
    "./src/google/protobuf/cpp_features.proto.pb.h",
};

// Definition for cpp_features_proto_files
std::vector<std::string> cpp_features_proto_files = {
    "./src/google/protobuf/cpp_features_proto-descriptor-set.proto.bin",
};

// Definition for descriptor_proto_proto_srcs
std::vector<std::string> descriptor_proto_proto_srcs = {
    "./src/google/protobuf/descriptor.proto",
};

// Definition for descriptor_proto_srcs
std::vector<std::string> descriptor_proto_srcs = {
    "./src/google/protobuf/descriptor.proto.pb.cc",
};

// Definition for descriptor_proto_hdrs
std::vector<std::string> descriptor_proto_hdrs = {
    "./src/google/protobuf/descriptor.proto.pb.h",
};

// Definition for descriptor_proto_files
std::vector<std::string> descriptor_proto_files = {
    "./src/google/protobuf/descriptor_proto-descriptor-set.proto.bin",
};

// Definition for plugin_proto_proto_srcs
std::vector<std::string> plugin_proto_proto_srcs = {
    "./src/google/protobuf/compiler/plugin.proto",
};

// Definition for plugin_proto_srcs
std::vector<std::string> plugin_proto_srcs = {
    "./src/google/protobuf/compiler/plugin.proto.pb.cc",
};

// Definition for plugin_proto_hdrs
std::vector<std::string> plugin_proto_hdrs = {
    "./src/google/protobuf/compiler/plugin.proto.pb.h",
};

// Definition for plugin_proto_files
std::vector<std::string> plugin_proto_files = {
    "./src/google/protobuf/compiler/plugin_proto-descriptor-set.proto.bin",
};

// Definition for java_features_proto_proto_srcs
std::vector<std::string> java_features_proto_proto_srcs = {
    "./java/core/src/main/resources/google/protobuf/java_features.proto",
};

// Definition for java_features_proto_srcs
std::vector<std::string> java_features_proto_srcs = {
    "./src/google/protobuf/compiler/java/java_features.proto.pb.cc",
};

// Definition for java_features_proto_hdrs
std::vector<std::string> java_features_proto_hdrs = {
    "./src/google/protobuf/compiler/java/java_features.proto.pb.h",
};

// Definition for java_features_proto_files
std::vector<std::string> java_features_proto_files = {
    "./java/core/java_features_proto-descriptor-set.proto.bin",
};

// Definition for common_test_srcs
std::vector<std::string> common_test_srcs = {
    "./src/google/protobuf/compiler/command_line_interface_tester.cc",
    "./src/google/protobuf/compiler/mock_code_generator.cc",
    "./src/google/protobuf/testing/file.cc",
    "./src/google/protobuf/testing/googletest.cc",
};

// Definition for common_test_hdrs
std::vector<std::string> common_test_hdrs = {
    "./src/google/protobuf/compiler/command_line_interface_tester.h",
    "./src/google/protobuf/compiler/mock_code_generator.h",
    "./src/google/protobuf/internal_visibility_for_testing.h",
    "./src/google/protobuf/test_textproto.h",
    "./src/google/protobuf/testing/googletest.h",
};

// Definition for lite_test_util_srcs
std::vector<std::string> lite_test_util_srcs = {
    "./src/google/protobuf/arena_test_util.cc",
    "./src/google/protobuf/map_lite_test_util.cc",
    "./src/google/protobuf/test_util_lite.cc",
};

// Definition for lite_test_util_hdrs
std::vector<std::string> lite_test_util_hdrs = {
    "./src/google/protobuf/arena_test_util.h",
    "./src/google/protobuf/map_lite_test_util.h",
    "./src/google/protobuf/map_test_util_impl.h",
    "./src/google/protobuf/proto3_lite_unittest.inc",
    "./src/google/protobuf/test_util.inc",
    "./src/google/protobuf/test_util2.h",
    "./src/google/protobuf/test_util_lite.h",
};

// Definition for test_util_srcs
std::vector<std::string> test_util_srcs = {
    "./src/google/protobuf/compiler/annotation_test_util.cc",
    "./src/google/protobuf/reflection_tester.cc",
    "./src/google/protobuf/test_util.cc",
    "./src/google/protobuf/testing/file.cc",
    "./src/google/protobuf/unredacted_debug_format_for_test.cc",
};

// Definition for test_util_hdrs
std::vector<std::string> test_util_hdrs = {
    "./src/google/protobuf/compiler/annotation_test_util.h",
    "./src/google/protobuf/compiler/cpp/unittest.h",
    "./src/google/protobuf/compiler/cpp/unittest.inc",
    "./src/google/protobuf/io/test_zero_copy_stream.h",
    "./src/google/protobuf/map_test.inc",
    "./src/google/protobuf/map_test_util.h",
    "./src/google/protobuf/map_test_util.inc",
    "./src/google/protobuf/message_unittest.inc",
    "./src/google/protobuf/message_unittest_legacy_apis.inc",
    "./src/google/protobuf/reflection_tester.h",
    "./src/google/protobuf/repeated_field_reflection_unittest.inc",
    "./src/google/protobuf/test_util.h",
    "./src/google/protobuf/test_util.inc",
    "./src/google/protobuf/unredacted_debug_format_for_test.h",
    "./src/google/protobuf/wire_format_unittest.inc",
};

// Definition for upb_test_util_files
std::vector<std::string> upb_test_util_files = {
    "./upb/test/fuzz_util.cc",
    "./upb/test/fuzz_util.h",
    "./upb/test/parse_text_proto.h",
    "./upb/util/def_to_proto_test.h",
};

// Definition for upb_test_protos_files
std::vector<std::string> upb_test_protos_files = {
    "./src/google/protobuf/any.proto",
    "./src/google/protobuf/api.proto",
    "./src/google/protobuf/duration.proto",
    "./src/google/protobuf/empty.proto",
    "./src/google/protobuf/field_mask.proto",
    "./src/google/protobuf/source_context.proto",
    "./src/google/protobuf/struct.proto",
    "./src/google/protobuf/test_messages_proto2.proto",
    "./src/google/protobuf/test_messages_proto3.proto",
    "./src/google/protobuf/timestamp.proto",
    "./src/google/protobuf/type.proto",
    "./src/google/protobuf/wrappers.proto",
    "./upb/json/test.proto",
    "./upb/message/test.proto",
    "./upb/message/utf8_test.proto",
    "./upb/message/utf8_test_proto2.proto",
    "./upb/test/editions_test.proto",
    "./upb/test/empty.proto",
    "./upb/test/proto3_test.proto",
    "./upb/test/test.proto",
    "./upb/test/test_cpp.proto",
    "./upb/test/test_import_empty_srcs.proto",
    "./upb/util/def_to_proto_editions_test.proto",
    "./upb/util/def_to_proto_public_import_test.proto",
    "./upb/util/def_to_proto_regular_import_test.proto",
    "./upb/util/def_to_proto_test.proto",
    "./upb/util/def_to_proto_weak_import_test.proto",
    "./upb/util/def_to_proto_wweak_import_test.proto",
    "./upb/util/required_fields_editions_test.proto",
    "./upb/util/required_fields_test.proto",
};

// Definition for upb_test_files
std::vector<std::string> upb_test_files = {
    "./upb/json/decode_test.cc",
    "./upb/json/encode_test.cc",
    "./upb/mem/arena_test.cc",
    "./upb/message/accessors_test.cc",
    "./upb/message/array_test.cc",
    "./upb/message/copy_test.cc",
    "./upb/message/internal/compare_unknown_test.cc",
    "./upb/message/map_test.cc",
    "./upb/message/merge_test.cc",
    "./upb/message/test.cc",
    "./upb/message/utf8_test.cc",
    "./upb/test/editions_test.cc",
    "./upb/test/length_prefixed_test.cc",
    "./upb/test/proto3_test.cc",
    "./upb/test/test_cpp.cc",
    "./upb/test/test_generated_code.cc",
    "./upb/test/test_import_empty_srcs.cc",
    "./upb/test/test_mini_table_oneof.cc",
    "./upb/util/def_to_proto_test.cc",
    "./upb/util/required_fields_test.cc",
    "./upb/wire/byte_size_test.cc",
    "./upb/wire/eps_copy_input_stream_test.cc",
};

// Definition for protobuf_test_files
std::vector<std::string> protobuf_test_files = {
    "./src/google/protobuf/any_test.cc",
    "./src/google/protobuf/arena_align_test.cc",
    "./src/google/protobuf/arena_unittest.cc",
    "./src/google/protobuf/arenastring_unittest.cc",
    "./src/google/protobuf/arenaz_sampler_test.cc",
    "./src/google/protobuf/debug_counter_test.cc",
    "./src/google/protobuf/descriptor_database_unittest.cc",
    "./src/google/protobuf/descriptor_unittest.cc",
    "./src/google/protobuf/descriptor_visitor_test.cc",
    "./src/google/protobuf/drop_unknown_fields_test.cc",
    "./src/google/protobuf/dynamic_message_unittest.cc",
    "./src/google/protobuf/edition_message_unittest.cc",
    "./src/google/protobuf/extension_set_unittest.cc",
    "./src/google/protobuf/feature_resolver_test.cc",
    "./src/google/protobuf/generated_enum_util_test.cc",
    "./src/google/protobuf/generated_message_reflection_unittest.cc",
    "./src/google/protobuf/generated_message_tctable_lite_test.cc",
    "./src/google/protobuf/has_bits_test.cc",
    "./src/google/protobuf/inlined_string_field_unittest.cc",
    "./src/google/protobuf/internal_message_util_unittest.cc",
    "./src/google/protobuf/map_field_test.cc",
    "./src/google/protobuf/map_test.cc",
    "./src/google/protobuf/message_unittest.cc",
    "./src/google/protobuf/no_field_presence_map_test.cc",
    "./src/google/protobuf/no_field_presence_test.cc",
    "./src/google/protobuf/port_test.cc",
    "./src/google/protobuf/preserve_unknown_enum_test.cc",
    "./src/google/protobuf/proto3_arena_lite_unittest.cc",
    "./src/google/protobuf/proto3_arena_unittest.cc",
    "./src/google/protobuf/proto3_lite_unittest.cc",
    "./src/google/protobuf/raw_ptr_test.cc",
    "./src/google/protobuf/redaction_metric_test.cc",
    "./src/google/protobuf/reflection_mode_test.cc",
    "./src/google/protobuf/reflection_ops_unittest.cc",
    "./src/google/protobuf/reflection_visit_fields_test.cc",
    "./src/google/protobuf/repeated_field_reflection_unittest.cc",
    "./src/google/protobuf/repeated_field_unittest.cc",
    "./src/google/protobuf/repeated_ptr_field_unittest.cc",
    "./src/google/protobuf/retention_test.cc",
    "./src/google/protobuf/string_block_test.cc",
    "./src/google/protobuf/string_piece_field_support_unittest.cc",
    "./src/google/protobuf/string_view_test.cc",
    "./src/google/protobuf/text_format_unittest.cc",
    "./src/google/protobuf/unknown_field_set_unittest.cc",
    "./src/google/protobuf/unredacted_debug_format_for_test.cc",
    "./src/google/protobuf/unredacted_debug_format_for_test_test.cc",
    "./src/google/protobuf/varint_shuffle_test.cc",
    "./src/google/protobuf/well_known_types_unittest.cc",
    "./src/google/protobuf/wire_format_unittest.cc",
};

// Definition for protobuf_test_protos_files
std::vector<std::string> protobuf_test_protos_files = {
    "./src/google/protobuf/any_test.proto",
    "./src/google/protobuf/edition_unittest.proto",
    "./src/google/protobuf/map_proto2_unittest.proto",
    "./src/google/protobuf/map_proto3_unittest.proto",
    "./src/google/protobuf/map_unittest.proto",
    "./src/google/protobuf/unittest.proto",
    "./src/google/protobuf/unittest_arena.proto",
    "./src/google/protobuf/unittest_custom_options.proto",
    "./src/google/protobuf/unittest_delimited.proto",
    "./src/google/protobuf/unittest_delimited_import.proto",
    "./src/google/protobuf/unittest_drop_unknown_fields.proto",
    "./src/google/protobuf/unittest_embed_optimize_for.proto",
    "./src/google/protobuf/unittest_empty.proto",
    "./src/google/protobuf/unittest_enormous_descriptor.proto",
    "./src/google/protobuf/unittest_features.proto",
    "./src/google/protobuf/unittest_import.proto",
    "./src/google/protobuf/unittest_import_public.proto",
    "./src/google/protobuf/unittest_invalid_features.proto",
    "./src/google/protobuf/unittest_lazy_dependencies.proto",
    "./src/google/protobuf/unittest_lazy_dependencies_custom_option.proto",
    "./src/google/protobuf/unittest_lazy_dependencies_enum.proto",
    "./src/google/protobuf/unittest_legacy_features.proto",
    "./src/google/protobuf/unittest_lite_imports_nonlite.proto",
    "./src/google/protobuf/unittest_mset.proto",
    "./src/google/protobuf/unittest_mset_wire_format.proto",
    "./src/google/protobuf/unittest_no_field_presence.proto",
    "./src/google/protobuf/unittest_no_generic_services.proto",
    "./src/google/protobuf/unittest_optimize_for.proto",
    "./src/google/protobuf/unittest_preserve_unknown_enum.proto",
    "./src/google/protobuf/unittest_preserve_unknown_enum2.proto",
    "./src/google/protobuf/unittest_proto3.proto",
    "./src/google/protobuf/unittest_proto3_arena.proto",
    "./src/google/protobuf/unittest_proto3_arena_lite.proto",
    "./src/google/protobuf/unittest_proto3_bad_macros.proto",
    "./src/google/protobuf/unittest_proto3_extensions.proto",
    "./src/google/protobuf/unittest_proto3_lite.proto",
    "./src/google/protobuf/unittest_proto3_optional.proto",
    "./src/google/protobuf/unittest_retention.proto",
    "./src/google/protobuf/unittest_string_type.proto",
    "./src/google/protobuf/unittest_string_view.proto",
    "./src/google/protobuf/unittest_well_known_types.proto",
};

// Definition for protobuf_lite_test_files
std::vector<std::string> protobuf_lite_test_files = {
    "./src/google/protobuf/lite_arena_unittest.cc",
    "./src/google/protobuf/lite_unittest.cc",
};

// Definition for protobuf_lite_test_protos_files
std::vector<std::string> protobuf_lite_test_protos_files = {
    "./src/google/protobuf/map_lite_unittest.proto",
    "./src/google/protobuf/unittest_import_lite.proto",
    "./src/google/protobuf/unittest_import_public_lite.proto",
    "./src/google/protobuf/unittest_lite.proto",
};

// Definition for fake_plugin_files
std::vector<std::string> fake_plugin_files = {
    "./src/google/protobuf/compiler/fake_plugin.cc",
};

// Definition for compiler_test_files
std::vector<std::string> compiler_test_files = {
    "./src/google/protobuf/compiler/code_generator_unittest.cc",
    "./src/google/protobuf/compiler/command_line_interface_unittest.cc",
    "./src/google/protobuf/compiler/cpp/arena_ctor_visibility_test.cc",
    "./src/google/protobuf/compiler/cpp/bootstrap_unittest.cc",
    "./src/google/protobuf/compiler/cpp/copy_unittest.cc",
    "./src/google/protobuf/compiler/cpp/file_unittest.cc",
    "./src/google/protobuf/compiler/cpp/generator_unittest.cc",
    "./src/google/protobuf/compiler/cpp/ifndef_guard_unittest.cc",
    "./src/google/protobuf/compiler/cpp/message_size_unittest.cc",
    "./src/google/protobuf/compiler/cpp/metadata_test.cc",
    "./src/google/protobuf/compiler/cpp/move_unittest.cc",
    "./src/google/protobuf/compiler/cpp/namespace_printer_unittest.cc",
    "./src/google/protobuf/compiler/cpp/plugin_unittest.cc",
    "./src/google/protobuf/compiler/cpp/unittest.cc",
    "./src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc",
    "./src/google/protobuf/compiler/csharp/csharp_generator_unittest.cc",
    "./src/google/protobuf/compiler/importer_unittest.cc",
    "./src/google/protobuf/compiler/java/doc_comment_unittest.cc",
    "./src/google/protobuf/compiler/java/message_serialization_unittest.cc",
    "./src/google/protobuf/compiler/java/plugin_unittest.cc",
    "./src/google/protobuf/compiler/objectivec/line_consumer_unittest.cc",
    "./src/google/protobuf/compiler/objectivec/names_unittest.cc",
    "./src/google/protobuf/compiler/objectivec/text_format_decode_data_unittest.cc",
    "./src/google/protobuf/compiler/parser_unittest.cc",
    "./src/google/protobuf/compiler/php/generator_unittest.cc",
    "./src/google/protobuf/compiler/python/plugin_unittest.cc",
    "./src/google/protobuf/compiler/retention_unittest.cc",
    "./src/google/protobuf/compiler/ruby/ruby_generator_unittest.cc",
    "./src/google/protobuf/compiler/versions_test.cc",
};

// Definition for compiler_test_protos_files
std::vector<std::string> compiler_test_protos_files = {
    "./src/google/protobuf/compiler/cpp/test_bad_identifiers.proto",
    "./src/google/protobuf/compiler/cpp/test_large_enum_value.proto",
};

// Definition for test_plugin_files
std::vector<std::string> test_plugin_files = {
    "./src/google/protobuf/compiler/test_plugin.cc",
};

// Definition for io_test_files
std::vector<std::string> io_test_files = {
    "./src/google/protobuf/io/coded_stream_unittest.cc",
    "./src/google/protobuf/io/io_win32_unittest.cc",
    "./src/google/protobuf/io/printer_death_test.cc",
    "./src/google/protobuf/io/printer_unittest.cc",
    "./src/google/protobuf/io/test_zero_copy_stream_test.cc",
    "./src/google/protobuf/io/tokenizer_unittest.cc",
    "./src/google/protobuf/io/zero_copy_sink_test.cc",
    "./src/google/protobuf/io/zero_copy_stream_unittest.cc",
};

// Definition for util_test_files
std::vector<std::string> util_test_files = {
    "./src/google/protobuf/util/delimited_message_util_test.cc",
    "./src/google/protobuf/util/field_comparator_test.cc",
    "./src/google/protobuf/util/field_mask_util_test.cc",
    "./src/google/protobuf/util/message_differencer_unittest.cc",
    "./src/google/protobuf/util/time_util_test.cc",
    "./src/google/protobuf/util/type_resolver_util_test.cc",
};

// Definition for util_test_protos_files
std::vector<std::string> util_test_protos_files = {
    "./src/google/protobuf/util/json_format.proto",
    "./src/google/protobuf/util/json_format_proto3.proto",
    "./src/google/protobuf/util/message_differencer_unittest.proto",
    "./src/google/protobuf/util/message_differencer_unittest_proto3.proto",
};

// Definition for stubs_test_files
std::vector<std::string> stubs_test_files = {
    "./src/google/protobuf/stubs/common_unittest.cc",
};

