#include <cgn>
#include "abseil-src.h"

// Abseil LTS 20260107.1
git("abseil-cpp.git", x) {
    x.repo = "https://github.com/abseil/abseil-cpp.git";
    x.commit_id = "255c84dadd029fd8ad25c5efb5933e47beaa00c7";
    x.dest_dir = "repo";
}

cmake("cmake_absl", x) {
    x.sources_dir = "repo";
    x.vars["ABSL_ENABLE_INSTALL"] = "ON";
    x.vars["ABSL_BUILD_TESTING"]  = "OFF";
    x.vars["ABSL_PROPAGATE_CXX_STD"] = "ON";

    if (x.cfg["os"] == "linux") {
        if (x.cfg["cxx_asan"] != "")
            x.vars["CMAKE_CXX_FLAGS"] += " -DADDRESS_SANITIZER";
        else if (x.cfg["cxx_lsan"] != "")
            x.vars["CMAKE_CXX_FLAGS"] += " -DLEAK_SANITIZER";

        x.outputs = {
            "lib64/libabsl_base.a", 
            "lib64/libabsl_borrowed_fixup_buffer.a", 
            "lib64/libabsl_city.a", 
            "lib64/libabsl_civil_time.a", 
            "lib64/libabsl_cord.a", 
            "lib64/libabsl_cord_internal.a", 
            "lib64/libabsl_cordz_functions.a", 
            "lib64/libabsl_cordz_handle.a", 
            "lib64/libabsl_cordz_info.a", 
            "lib64/libabsl_cordz_sample_token.a", 
            "lib64/libabsl_crc32c.a", 
            "lib64/libabsl_crc_cord_state.a", 
            "lib64/libabsl_crc_cpu_detect.a", 
            "lib64/libabsl_crc_internal.a", 
            "lib64/libabsl_debugging_internal.a", 
            "lib64/libabsl_decode_rust_punycode.a", 
            "lib64/libabsl_demangle_internal.a", 
            "lib64/libabsl_demangle_rust.a", 
            "lib64/libabsl_die_if_null.a", 
            "lib64/libabsl_examine_stack.a", 
            "lib64/libabsl_exponential_biased.a", 
            "lib64/libabsl_failure_signal_handler.a", 
            "lib64/libabsl_flags_commandlineflag.a", 
            "lib64/libabsl_flags_commandlineflag_internal.a", 
            "lib64/libabsl_flags_config.a", 
            "lib64/libabsl_flags_internal.a", 
            "lib64/libabsl_flags_marshalling.a", 
            "lib64/libabsl_flags_parse.a", 
            "lib64/libabsl_flags_private_handle_accessor.a", 
            "lib64/libabsl_flags_program_name.a", 
            "lib64/libabsl_flags_reflection.a", 
            "lib64/libabsl_flags_usage.a", 
            "lib64/libabsl_flags_usage_internal.a", 
            "lib64/libabsl_generic_printer_internal.a", 
            "lib64/libabsl_graphcycles_internal.a", 
            "lib64/libabsl_hash.a", 
            "lib64/libabsl_hashtable_profiler.a", 
            "lib64/libabsl_hashtablez_sampler.a", 
            "lib64/libabsl_int128.a", 
            "lib64/libabsl_kernel_timeout_internal.a", 
            "lib64/libabsl_leak_check.a", 
            "lib64/libabsl_log_entry.a", 
            "lib64/libabsl_log_flags.a", 
            "lib64/libabsl_log_globals.a", 
            "lib64/libabsl_log_initialize.a", 
            "lib64/libabsl_log_internal_check_op.a", 
            "lib64/libabsl_log_internal_conditions.a", 
            "lib64/libabsl_log_internal_fnmatch.a", 
            "lib64/libabsl_log_internal_format.a", 
            "lib64/libabsl_log_internal_globals.a", 
            "lib64/libabsl_log_internal_log_sink_set.a", 
            "lib64/libabsl_log_internal_message.a", 
            "lib64/libabsl_log_internal_nullguard.a", 
            "lib64/libabsl_log_internal_proto.a", 
            "lib64/libabsl_log_internal_structured_proto.a", 
            "lib64/libabsl_log_severity.a", 
            "lib64/libabsl_log_sink.a", 
            "lib64/libabsl_malloc_internal.a", 
            "lib64/libabsl_periodic_sampler.a", 
            "lib64/libabsl_poison.a", 
            "lib64/libabsl_profile_builder.a", 
            "lib64/libabsl_random_distributions.a", 
            "lib64/libabsl_random_internal_distribution_test_util.a", 
            "lib64/libabsl_random_internal_entropy_pool.a", 
            "lib64/libabsl_random_internal_platform.a", 
            "lib64/libabsl_random_internal_randen.a", 
            "lib64/libabsl_random_internal_randen_hwaes.a", 
            "lib64/libabsl_random_internal_randen_hwaes_impl.a", 
            "lib64/libabsl_random_internal_randen_slow.a", 
            "lib64/libabsl_random_internal_seed_material.a", 
            "lib64/libabsl_random_seed_gen_exception.a", 
            "lib64/libabsl_random_seed_sequences.a", 
            "lib64/libabsl_raw_hash_set.a", 
            "lib64/libabsl_raw_logging_internal.a", 
            "lib64/libabsl_scoped_set_env.a", 
            "lib64/libabsl_spinlock_wait.a", 
            "lib64/libabsl_stacktrace.a", 
            "lib64/libabsl_status.a", 
            "lib64/libabsl_statusor.a", 
            "lib64/libabsl_strerror.a", 
            "lib64/libabsl_str_format_internal.a", 
            "lib64/libabsl_strings.a", 
            "lib64/libabsl_strings_internal.a", 
            "lib64/libabsl_symbolize.a", 
            "lib64/libabsl_synchronization.a", 
            "lib64/libabsl_throw_delegate.a", 
            "lib64/libabsl_time.a", 
            "lib64/libabsl_time_zone.a", 
            "lib64/libabsl_tracing_internal.a", 
            "lib64/libabsl_utf8_for_code_point.a", 
            "lib64/libabsl_vlog_config_internal.a",
        };
    } //endif (os == "linux")

    if (x.cfg["os"] == "win") {
        x.outputs = {
            "lib/absl_bad_any_cast_impl.lib",
            "lib/absl_bad_optional_access.lib",
            "lib/absl_bad_variant_access.lib",
            "lib/absl_base.lib",
            "lib/absl_city.lib",
            "lib/absl_civil_time.lib",
            "lib/absl_cord.lib",
            "lib/absl_cordz_functions.lib",
            "lib/absl_cordz_handle.lib",
            "lib/absl_cordz_info.lib",
            "lib/absl_cordz_sample_token.lib",
            "lib/absl_cord_internal.lib",
            "lib/absl_crc32c.lib",
            "lib/absl_crc_cord_state.lib",
            "lib/absl_crc_cpu_detect.lib",
            "lib/absl_crc_internal.lib",
            "lib/absl_debugging_internal.lib",
            "lib/absl_decode_rust_punycode.lib",
            "lib/absl_demangle_internal.lib",
            "lib/absl_demangle_rust.lib",
            "lib/absl_die_if_null.lib",
            "lib/absl_examine_stack.lib",
            "lib/absl_exponential_biased.lib",
            "lib/absl_failure_signal_handler.lib",
            "lib/absl_flags_commandlineflag.lib",
            "lib/absl_flags_commandlineflag_internal.lib",
            "lib/absl_flags_config.lib",
            "lib/absl_flags_internal.lib",
            "lib/absl_flags_marshalling.lib",
            "lib/absl_flags_parse.lib",
            "lib/absl_flags_private_handle_accessor.lib",
            "lib/absl_flags_program_name.lib",
            "lib/absl_flags_reflection.lib",
            "lib/absl_flags_usage.lib",
            "lib/absl_flags_usage_internal.lib",
            "lib/absl_graphcycles_internal.lib",
            "lib/absl_hash.lib",
            "lib/absl_hashtablez_sampler.lib",
            "lib/absl_int128.lib",
            "lib/absl_kernel_timeout_internal.lib",
            "lib/absl_leak_check.lib",
            "lib/absl_log_entry.lib",
            "lib/absl_log_flags.lib",
            "lib/absl_log_globals.lib",
            "lib/absl_log_initialize.lib",
            "lib/absl_log_internal_check_op.lib",
            "lib/absl_log_internal_conditions.lib",
            "lib/absl_log_internal_fnmatch.lib",
            "lib/absl_log_internal_format.lib",
            "lib/absl_log_internal_globals.lib",
            "lib/absl_log_internal_log_sink_set.lib",
            "lib/absl_log_internal_message.lib",
            "lib/absl_log_internal_nullguard.lib",
            "lib/absl_log_internal_proto.lib",
            "lib/absl_log_severity.lib",
            "lib/absl_log_sink.lib",
            "lib/absl_low_level_hash.lib",
            "lib/absl_malloc_internal.lib",
            "lib/absl_periodic_sampler.lib",
            "lib/absl_poison.lib",
            "lib/absl_random_distributions.lib",
            "lib/absl_random_internal_distribution_test_util.lib",
            "lib/absl_random_internal_platform.lib",
            "lib/absl_random_internal_pool_urbg.lib",
            "lib/absl_random_internal_randen.lib",
            "lib/absl_random_internal_randen_hwaes.lib",
            "lib/absl_random_internal_randen_hwaes_impl.lib",
            "lib/absl_random_internal_randen_slow.lib",
            "lib/absl_random_internal_seed_material.lib",
            "lib/absl_random_seed_gen_exception.lib",
            "lib/absl_random_seed_sequences.lib",
            "lib/absl_raw_hash_set.lib",
            "lib/absl_raw_logging_internal.lib",
            "lib/absl_scoped_set_env.lib",
            "lib/absl_spinlock_wait.lib",
            "lib/absl_stacktrace.lib",
            "lib/absl_status.lib",
            "lib/absl_statusor.lib",
            "lib/absl_strerror.lib",
            "lib/absl_strings.lib",
            "lib/absl_strings_internal.lib",
            "lib/absl_string_view.lib",
            "lib/absl_str_format_internal.lib",
            "lib/absl_symbolize.lib",
            "lib/absl_synchronization.lib",
            "lib/absl_throw_delegate.lib",
            "lib/absl_time.lib",
            "lib/absl_time_zone.lib",
            "lib/absl_utf8_for_code_point.lib",
            "lib/absl_vlog_config_internal.lib",
        };
    }

} //cmake("cmake_absl")

// TODO: This parser is too slow to commit, we use ":cmake_absl" for current stage.
// parse abseil-src.h to define targets.
// #include "abseil-target_define.hxx"

alias("abseil-cpp", x) {
    // x.actual_label = ":all";
    x.actual_label = ":cmake_absl";
}
