; This file is auto generated by cgn::MSVCTrampo

.const
  msvc_trampo_0 DB "?func1_inc@@YAHAEAH@Z",0
  msvc_trampo_1 DB "?func1@@YA?AUMyTypeA@@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z",0
  msvc_trampo_2 DB "?func1_arr@@YA?AV?$vector@UMyTypeA@@V?$allocator@UMyTypeA@@@std@@@std@@PEBUMyTypeA@@@Z",0
end

.code
  ?func1_inc@@YAHAEAH@Z PROC
    push msvc_trampo_0
    call ?find@GlobalSymbol@cgn@@SAPEAXPEBD@Z
    add rsp, 4
    jmp rax
  ?func1_inc@@YAHAEAH@Z ENDP

  ?func1@@YA?AUMyTypeA@@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z PROC
    push msvc_trampo_1
    call ?find@GlobalSymbol@cgn@@SAPEAXPEBD@Z
    add rsp, 4
    jmp rax
  ?func1@@YA?AUMyTypeA@@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z ENDP

  ?func1_arr@@YA?AV?$vector@UMyTypeA@@V?$allocator@UMyTypeA@@@std@@@std@@PEBUMyTypeA@@@Z PROC
    push msvc_trampo_2
    call ?find@GlobalSymbol@cgn@@SAPEAXPEBD@Z
    add rsp, 4
    jmp rax
  ?func1_arr@@YA?AV?$vector@UMyTypeA@@V?$allocator@UMyTypeA@@@std@@@std@@PEBUMyTypeA@@@Z ENDP

end
